apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: mern-blog
spec:
  selector:
    app: frontend
  ports:
    - port: 80
      targetPort: {{ .Values.frontend.port }}
  type: ClusterIP