name: Deploy backend
on:
  push:
    branches: [main]
    paths:
      - "backend/**"
      - "helm/backend/**"
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Run tests
        run: echo "test OK"

  build:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v7

      - name: Login to Docker Hub
        uses: docker/login-action@v4
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build image
        run: docker build -t ${{ vars.DOCKERHUB_USERNAME }}/blog-backend:${{ github.sha }} ./backend

      - name: Push image to Docker Hub
        run: docker push ${{ vars.DOCKERHUB_USERNAME }}/blog-backend:${{ github.sha }}

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v7

      - name: Configure AWS OIDC
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/${{ vars.OIDC_ROLE_NAME }}
          aws-region: ${{ vars.AWS_REGION }}

      - name: Update kubeconfig
        run: aws eks update-kubeconfig --name ${{ vars.EKS_CLUSTER_NAME }} --region ${{ vars.AWS_REGION }}

      - name: Deploy with Helm
        run: |
          helm upgrade --install mern-backend ./helm/backend \
            --namespace mern-blog \
            --create-namespace \
            --set backend.image.tag=${{ github.sha }}
