frontend:
  image:
    repository: rahulr45/blog-frontend
    tag: latest
  replicas: 1
  port: 80
  env:
    VITE_API_URL: "http://k8s-mernblog-merningr-a3dcfa66e8-1298005677.ap-south-1.elb.amazonaws.com/api"
  resources:
    requests:
      cpu: "100m"
      memory: "128Mi"
    limits:
      cpu: "250m"
      memory: "256Mi"

backend:
  port: 5000